#!/usr/bin/env python

"""
a script translate cif file to POSCAR file
"""

import os
import fileinput
import sys
import re
import string
import shutil
from pymatgen.io.vaspio.vasp_output import Vasprun
from pymatgen.io.vaspio.vasp_input import Poscar
from pymatgen.core.periodic_table import Element
from  pymatgen.io.vaspio_set import MPVaspInputSet
from pymatgen.core.surface import Slab
from pymatgen.core.surface import SlabGenerator
from pymatgen.io.cifio import CifParser

def cif_to_poscar(cif_filename):
    cp = CifParser(cif_filename)
    structure = cp.get_structures(primitive=False)[0]
    pos = Poscar(structure)
    pos.write_file('POSCAR')
    print "write POSCAR to current location!"

if __name__ == "__main__":
    cif_to_poscar(sys.argv[1])

